version: "2"
services:
  elasticsearhc_client:
    image: angelfym/php-nginx-aws:latest
    volumes:
      - ./src:/usr/src/
    command: ping 127.0.0.1
    links:
      - elasticsearch
      - kibana
  elasticsearch:
    image: elasticsearch:5.4.0
    container_name: elasticsearch_local_node
    ports:
      - 9200:9200
  kibana:
    image: kibana:5.4.0
    container_name: kibana_local_node
    ports:
      - 5601:5601
    links:
      - elasticsearch