version: "2"
services:
  elasticsearch:
    image: elasticsearch:5.4.0
    container_name: elasticsearch_local_node
    ports:
      - 9200:9200
  kibana:
    image: kibana:5.4.0
    container_name: kibana_local_node
    ports:
      - 5601:5601
    links:
      - elasticsearch